In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/English Premier League - Player Stats - 24:25/epl_player_stats_24_25.csv")

In [3]:
df[["Player Name", "Goals"]].head()

     Player Name  Goals
0      Ben White      0
1    Bukayo Saka      6
2     David Raya      0
3    Declan Rice      4
4  Ethan Nwaneri      4

In [4]:
df[
    (df["Minutes"] > 900) &
    (df["Position"] == "FWD")
    ][["Player Name", "Club", "Position", "Minutes", "Goals"]].head(30)

               Player Name                    Club Position  Minutes  Goals
11             Kai Havertz                 Arsenal      FWD     1874      9
46           Ollie Watkins             Aston Villa      FWD     2610     16
61               Evanilson             Bournemouth      FWD     2335      0
107            Yoane Wissa               Brentford      FWD     2927     19
116          Danny Welbeck  Brighton & Hove Albion      FWD     2122     10
127             João Pedro  Brighton & Hove Albion      FWD     1953     10
129           Kaoru Mitoma  Brighton & Hove Albion      FWD     2608     10
155        Nicolas Jackson                 Chelsea      FWD     2238     10
178          Eddie Nketiah          Crystal Palace      FWD     1026      3
180   Jean-Philippe Mateta          Crystal Palace      FWD     2654     14
194         Adam Armstrong                 Everton      FWD     1252      2
197                   Beto                 Everton      FWD     1528      8
199  Dominic Calvert-Lewin                 Everton      FWD     1613      3
203          Iliman Ndiaye                 Everton      FWD     2440      9
236           Raúl Jiménez                  Fulham      FWD     2505      0
238          Rodrigo Muniz                  Fulham      FWD      951      8
259            Jack Clarke            Ipswich Town      FWD     1170      0
267             Liam Delap            Ipswich Town      FWD     2612      0
274           Sam Szmodics            Ipswich Town      FWD     1001      4
288            Jamie Vardy          Leicester City      FWD     2839      9
310             Cody Gakpo               Liverpool      FWD     1938     10
313           Darwin Núñez               Liverpool      FWD     1118      5
314             Diogo Jota               Liverpool      FWD     1194      6
335         Erling Haaland         Manchester City      FWD     2741     22
351          Omar Marmoush         Manchester City      FWD     1182      7
357                Savinho         Manchester City      FWD     1770      1
375         Joshua Zirkzee       Manchester United      FWD     1392      3
385         Rasmus Højlund       Manchester United      FWD     2013      4
391         Alexander Isak        Newcastle United      FWD     2769     23
417             Chris Wood       Nottingham Forest      FWD     2976     20

In [5]:
df["Conversion %"] = df["Conversion %"].str.rstrip("%").astype(float)

In [6]:
df[
    (df["Shots"] > 5) &
    (df["Conversion %"] > 10)
]

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
0,Ben White,Arsenal,England,DEF,17,1198,0,2,9,12,...,10,2,0,0,0%,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
3,Declan Rice,Arsenal,England,MID,35,2833,4,7,48,18,...,21,5,1,0,0%,0,0,0,0,0.0
6,Gabriel Magalhães,Arsenal,Brazil,DEF,28,2365,3,1,22,25,...,19,4,0,0,0%,0,0,0,0,0.0
10,Jurriën Timber,Arsenal,Netherlands,DEF,30,2422,1,3,14,34,...,0,7,0,0,0%,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Lucas Paquetá,West Ham United,Brazil,MID,33,2384,4,0,41,30,...,53,10,0,0,0%,0,0,0,0,0.0
522,Maximilian Kilman,West Ham United,England,DEF,38,3349,0,1,13,4,...,23,5,0,0,0%,0,0,0,0,0.0
538,Emmanuel Agbadou,Wolverhampton Wanderers,Cote D’Ivoire,DEF,16,1411,1,0,7,20,...,7,3,0,0,0%,0,0,0,0,0.0
543,Jørgen Strand Larsen,Wolverhampton Wanderers,Norway,FWD,35,2599,0,0,54,29,...,46,4,0,0,0%,0,0,0,0,0.0
548,Matheus Cunha,Wolverhampton Wanderers,Brazil,MID,33,2600,15,6,110,4,...,42,4,0,0,0%,0,0,0,0,0.0

In [7]:
forwards = df[
    (df["Minutes"] > 900)
    ].to_clipboard(index=False, header=True)

In [8]:
filtered_df = df[
    (df["Minutes"] >= 900) &
    (df["Position"] == "FWD")
]

filtered_df.to_excel("forwards_900min.xlsx", index=False)

In [102]:
df[
    (df["Minutes"] >= 900) &
    (df["Position"] == "FWD")
][["Player Name", "Club", "Position", "Goals", "Assists", "Shots", "Conversion %"]]

,Player Name,Club,Position,Goals,Assists,Shots,Conversion %
11,Kai Havertz,Arsenal,FWD,9,3,53,0.0
46,Ollie Watkins,Aston Villa,FWD,16,8,84,14.0
61,Evanilson,Bournemouth,FWD,0,1,73,18.0
107,Yoane Wissa,Brentford,FWD,19,0,90,7.0
116,Danny Welbeck,Brighton & Hove Albion,FWD,10,0,60,0.0
127,João Pedro,Brighton & Hove Albion,FWD,10,0,47,3.0
129,Kaoru Mitoma,Brighton & Hove Albion,FWD,10,4,57,4.0
155,Nicolas Jackson,Chelsea,FWD,10,5,76,9.0
178,Eddie Nketiah,Crystal Palace,FWD,3,0,43,0.0
180,Jean-Philippe Mateta,Crystal Palace,FWD,14,2,70,9.0
194,Adam Armstrong,Everton,FWD,2,2,26,8.0
197,Beto,Everton,FWD,8,0,49,7.0
199,Dominic Calvert-Lewin,Everton,FWD,3,1,50,15.0
203,Iliman Ndiaye,Everton,FWD,9,0,37,4.0
236,Raúl Jiménez,Fulham,FWD,0,3,96,13.0
238,Rodrigo Muniz,Fulham,FWD,8,1,39,6.0
259,Jack Clarke,Ipswich Town,FWD,0,4,17,3.0
267,Liam Delap,Ipswich Town,FWD,0,2,68,12.0
274,Sam Szmodics,Ipswich Town,FWD,4,0,21,0.0
288,Jamie Vardy,Leicester City,FWD,9,0,58,40.0
310,Cody Gakpo,Liverpool,FWD,10,4,57,12.0
313,Darwin Núñez,Liverpool,FWD,5,0,34,8.0
314,Diogo Jota,Liverpool,FWD,6,3,51,10.0
335,Erling Haaland,Manchester City,FWD,22,3,108,20.0
351,Omar Marmoush,Manchester City,FWD,7,0,49,7.0
357,Savinho,Manchester City,FWD,1,8,55,0.0
375,Joshua Zirkzee,Manchester United,FWD,3,0,28,4.0
385,Rasmus Højlund,Manchester United,FWD,4,0,32,11.0
391,Alexander Isak,Newcastle United,FWD,23,0,99,13.0
417,Chris Wood,Nottingham Forest,FWD,20,3,68,7.0
443,Cameron Archer,Southampton,FWD,2,0,29,0.0
459,Paul Onuachu,Southampton,FWD,4,0,34,7.0
467,Tyler Dibling,Southampton,FWD,2,0,28,0.0
482,Dominic Solanke,Tottenham Hotspur,FWD,9,3,60,9.0
488,Mathys Tel,Tottenham Hotspur,FWD,2,0,23,11.0
543,Jørgen Strand Larsen,Wolverhampton Wanderers,FWD,0,0,54,19.0

In [9]:
df[
    (df["Shots"] >= 40) &
    (df["Conversion %"] >= 15)
]

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
3,Declan Rice,Arsenal,England,MID,35,2833,4,7,48,18,...,21,5,1,0,0%,0,0,0,0,0.0
61,Evanilson,Bournemouth,Brazil,FWD,31,2335,0,1,73,5,...,37,1,1,0,0%,0,0,0,0,0.0
66,Justin Kluivert,Bournemouth,Netherlands,MID,34,2356,0,0,63,21,...,47,8,0,0,0%,0,0,0,0,0.0
141,Cole Palmer,Chelsea,England,MID,37,3195,15,8,126,2,...,15,7,0,0,0%,0,0,0,0,0.0
142,Enzo Fernández,Chelsea,Argentina,MID,36,2946,6,7,53,60,...,52,8,0,0,0%,0,0,0,0,0.0
199,Dominic Calvert-Lewin,Everton,England,FWD,26,1613,3,1,50,26,...,27,2,0,0,0%,0,0,0,0,0.0
288,Jamie Vardy,Leicester City,England,FWD,35,2839,9,0,58,3,...,25,5,0,0,0%,0,0,0,0,0.0
315,Dominik Szoboszlai,Liverpool,Hungary,MID,36,2496,6,6,67,10,...,44,6,0,0,0%,0,0,0,0,0.0
326,Trent Alexander-Arnold,Liverpool,England,DEF,33,2377,3,6,45,7,...,11,5,0,0,0%,0,0,0,0,0.0
335,Erling Haaland,Manchester City,Norway,FWD,31,2741,22,3,108,6,...,24,2,0,0,0%,0,0,0,0,0.0
343,Kevin De Bruyne,Manchester City,Belgium,MID,28,1704,4,7,57,27,...,17,2,0,0,0%,0,0,0,0,0.0
363,Amad Diallo,Manchester United,Cote D’Ivoire,MID,26,1901,8,6,47,6,...,21,5,0,0,0%,0,0,0,0,0.0
393,Bruno Guimarães,Newcastle United,Brazil,MID,38,3282,5,0,45,41,...,65,7,0,0,0%,0,0,0,0,0.0
426,Morgan Gibbs-White,Nottingham Forest,England,MID,34,2822,7,8,61,20,...,38,9,1,0,0%,0,0,0,0,0.0
497,Son Heung-Min,Tottenham Hotspur,South Korea,MID,30,2116,7,9,57,7,...,6,1,0,0,0%,0,0,0,0,0.0
519,Lucas Paquetá,West Ham United,Brazil,MID,33,2384,4,0,41,30,...,53,10,0,0,0%,0,0,0,0,0.0
543,Jørgen Strand Larsen,Wolverhampton Wanderers,Norway,FWD,35,2599,0,0,54,29,...,46,4,0,0,0%,0,0,0,0,0.0

In [10]:
df[
    (df["Minutes"] >= 900) &
    (df["Shots"] >= 50)
].sort_values("Shots", ascending=False)

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
324,Mohamed Salah,Liverpool,Egypt,MID,38,3377,29,18,130,22,...,25,1,0,0,0%,0,0,0,0,0.0
141,Cole Palmer,Chelsea,England,MID,37,3195,15,8,126,2,...,15,7,0,0,0%,0,0,0,0,0.0
54,Antoine Semenyo,Bournemouth,Ghana,MID,37,3209,0,5,125,2,...,73,9,0,0,0%,0,0,0,0,0.0
548,Matheus Cunha,Wolverhampton Wanderers,Brazil,MID,33,2600,15,6,110,4,...,42,4,0,0,0%,0,0,0,0,0.0
335,Erling Haaland,Manchester City,Norway,FWD,31,2741,22,3,108,6,...,24,2,0,0,0%,0,0,0,0,0.0
177,Eberechi Eze,Crystal Palace,England,MID,34,2600,8,8,102,16,...,13,1,0,0,0%,0,0,0,0,0.0
391,Alexander Isak,Newcastle United,Sweden,FWD,34,2769,23,0,99,14,...,27,1,0,0,0%,0,0,0,0,0.0
367,Bruno Fernandes,Manchester United,Portugal,MID,36,3024,8,10,96,15,...,32,3,2,0,0%,0,0,0,0,0.0
236,Raúl Jiménez,Fulham,Mexico,FWD,38,2505,0,3,96,33,...,39,4,0,0,0%,0,0,0,0,0.0
107,Yoane Wissa,Brentford,DR Congo,FWD,35,2927,19,0,90,13,...,34,5,0,0,0%,0,0,0,0,0.0
514,Jarrod Bowen,West Ham United,England,MID,34,2979,0,8,87,0,...,20,1,0,0,0%,0,0,0,0,0.0
82,Bryan Mbeumo,Brentford,Cameroon,MID,38,3415,20,7,85,23,...,25,3,0,0,0%,0,0,0,0,0.0
361,Alejandro Garnacho,Manchester United,Argentina,MID,36,2195,6,2,84,30,...,12,3,0,0,0%,0,0,0,0,0.0
46,Ollie Watkins,Aston Villa,England,FWD,38,2610,16,8,84,17,...,29,2,0,0,0%,0,0,0,0,0.0
156,Noni Madueke,Chelsea,England,MID,32,2046,7,3,80,7,...,22,3,0,0,0%,0,0,0,0,0.0
155,Nicolas Jackson,Chelsea,Senegal,FWD,30,2238,10,5,76,32,...,35,7,1,0,0%,0,0,0,0,0.0
525,Mohammed Kudus,West Ham United,Ghana,MID,32,2601,5,3,75,3,...,39,2,1,0,0%,0,0,0,0,0.0
61,Evanilson,Bournemouth,Brazil,FWD,31,2335,0,1,73,5,...,37,1,1,0,0%,0,0,0,0,0.0
13,Leandro Trossard,Arsenal,Belgium,MID,38,2550,8,7,72,2,...,27,2,1,0,0%,0,0,0,0,0.0
323,Luis Díaz,Liverpool,Colombia,MID,36,2410,0,5,71,0,...,48,2,0,0,0%,0,0,0,0,0.0
180,Jean-Philippe Mateta,Crystal Palace,France,FWD,37,2654,14,2,70,5,...,27,2,0,0,0%,0,0,0,0,0.0
220,Alex Iwobi,Fulham,Nigeria,MID,38,2994,9,0,68,29,...,19,1,0,0,0%,0,0,0,0,0.0
267,Liam Delap,Ipswich Town,England,FWD,37,2612,0,2,68,6,...,72,12,0,0,0%,0,0,0,0,0.0
417,Chris Wood,Nottingham Forest,New Zealand,FWD,36,2976,20,3,68,2,...,25,1,0,0,0%,0,1,0,0,0.0
315,Dominik Szoboszlai,Liverpool,Hungary,MID,36,2496,6,6,67,10,...,44,6,0,0,0%,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
398,Harvey Barnes,Newcastle United,England,MID,33,1755,9,4,63,5,...,15,0,0,0,0%,0,0,0,0,0.0
66,Justin Kluivert,Bournemouth,Netherlands,MID,34,2356,0,0,63,21,...,47,8,0,0,0%,0,0,0,0,0.0
56,Dango Ouattara,Bournemouth,Burkina Faso,MID,32,2006,7,0,62,18,...,16,3,0,0,0%,0,0,0,0,0.0
426,Morgan Gibbs-White,Nottingham Forest,England,MID,34,2822,7,8,61,20,...,38,9,1,0,0%,0,0,0,0,0.0
116,Danny Welbeck,Brighton & Hove Albion,England,FWD,30,2122,10,0,60,2,...,11,5,0,0,0%,0,0,0,0,0.0
482,Dominic Solanke,Tottenham Hotspur,England,FWD,27,2206,9,3,60,23,...,36,0,0,0,0%,0,0,0,0,0.0
392,Anthony Gordon,Newcastle United,England,MID,34,2444,6,5,59,41,...,20,2,0,0,0%,0,0,0,0,0.0
179,Ismaïla Sarr,Crystal Palace,Senegal,MID,38,2714,8,6,59,2,...,14,4,0,0,0%,0,2,0,0,0.0
157,Pedro Neto,Chelsea,Portugal,MID,35,2268,4,0,59,8,...,21,8,0,0,0%,0,0,0,0,0.0
288,Jamie Vardy,Leicester City,England,FWD,35,2839,9,0,58,3,...,25,5,0,0,0%,0,0,0,0,0.0
310,Cody Gakpo,Liverpool,Netherlands,FWD,35,1938,10,4,57,51,...,20,5,0,0,0%,0,0,0,0,0.0
72,Marcus Tavernier,Bournemouth,England,MID,29,1938,3,5,57,5,...,34,6,0,0,0%,0,0,0,0,0.0
497,Son Heung-Min,Tottenham Hotspur,South Korea,MID,30,2116,7,9,57,7,...,6,1,0,0,0%,0,0,0,0,0.0
343,Kevin De Bruyne,Manchester City,Belgium,MID,28,1704,4,7,57,27,...,17,2,0,0,0%,0,0,0,0,0.0
129,Kaoru Mitoma,Brighton & Hove Albion,Japan,FWD,36,2608,10,4,57,14,...,40,1,0,0,0%,0,0,0,0,0.0
528,Tomás Soucek,West Ham United,Czech Republic,MID,35,2570,9,0,55,2,...,47,8,0,0,0%,0,0,0,0,0.0
357,Savinho,Manchester City,Brazil,FWD,29,1770,1,8,55,6,...,17,3,0,0,0%,0,0,0,0,0.0
7,Gabriel Martinelli,Arsenal,Brazil,MID,33,2300,8,4,55,12,...,16,1,0,0,0%,0,0,0,0,0.0
92,Kevin Schade,Brentford,Germany,MID,38,2301,0,2,55,0,...,21,3,0,0,0%,0,0,0,0,0.0
45,Morgan Rogers,Aston Villa,England,MID,37,3129,8,10,55,6,...,50,10,0,0,0%,0,0,0,0,0.0
353,Phil Foden,Manchester City,England,MID,28,1779,7,2,54,1,...,5,2,0,0,0%,0,0,0,0,0.0
476,Brennan Johnson,Tottenham Hotspur,Wales,MID,33,2179,0,3,54,29,...,27,5,0,0,0%,0,0,0,0,0.0
543,Jørgen Strand Larsen,Wolverhampton Wanderers,Norway,FWD,35,2599,0,0,54,29,...,46,4,0,0,0%,0,0,0,0,0.0
11,Kai Havertz,Arsenal,Germany,FWD,23,1874,9,3,53,2,...,38,5,0,0,0%,0,0,0,0,0.0
142,Enzo Fernández,Chelsea,Argentina,MID,36,2946,6,7,53,60,...,52,8,0,0,0%,0,0,0,0,0.0
264,Julio Enciso,Ipswich Town,Paraguay,MID,25,1164,2,3,52,9,...,12,3,0,0,0%,0,0,0,0,0.0
314,Diogo Jota,Liverpool,Portugal,FWD,26,1194,6,3,51,3,...,23,2,0,0,0%,0,0,0,0,0.0
120,Georginio Rutter,Brighton & Hove Albion,France,MID,28,1666,5,3,50,8,...,34,2,0,0,0%,0,0,0,0,0.0
199,Dominic Calvert-Lewin,Everton,England,FWD,26,1613,3,1,50,26,...,27,2,0,0,0%,0,0,0,0,0.0

In [21]:
df[
    (df["Minutes"] < 300) &
    (df["Conversion %"] > 10)
]

Empty DataFrame
Columns: [Player Name, Club, Nationality, Position, Appearances, Minutes, Goals, Assists, Shots, Shots On Target, Conversion %, Big Chances Missed, Hit Woodwork, Offsides, Touches, Passes, Successful Passes, Passes%, Crosses, Successful Crosses, Crosses %, fThird Passes, Successful fThird Passes, fThird Passes %, Through Balls, Carries, Progressive Carries, Carries Ended with Goal, Carries Ended with Assist, Carries Ended with Shot, Carries Ended with Chance, Possession Won, Dispossessed, Clean Sheets, Clearances, Interceptions, Blocks, Tackles, Ground Duels, gDuels Won, gDuels %, Aerial Duels, aDuels Won, aDuels %, Goals Conceded, xGoT Conceded, Own Goals, Fouls, Yellow Cards, Red Cards, Saves, Saves %, Penalties Saved, Clearances Off Line, Punches, High Claims, Goals Prevented]
Index: []

[0 rows x 57 columns]

In [23]:
df[
    df["Club"] == "Arsenal"
][["Player Name", "Position", "Minutes", "Goals", "Assists", "Shots"]].sort_values("Shots", ascending=False)

              Player Name Position  Minutes  Goals  Assists  Shots
13       Leandro Trossard      MID     2550      8        7     72
1             Bukayo Saka      MID     1735      6       10     67
7      Gabriel Martinelli      MID     2300      8        4     55
11            Kai Havertz      FWD     1874      9        3     53
14        Martin Ødegaard      MID     2328      3        8     49
3             Declan Rice      MID     2833      4        7     48
15           Mikel Merino      MID     1581      7        2     38
23          Thomas Partey      MID     2799      4        0     26
4           Ethan Nwaneri      MID      889      4        0     24
6       Gabriel Magalhães      DEF     2365      3        1     22
5           Gabriel Jesus      FWD      603      3        0     20
10         Jurriën Timber      DEF     2422      1        3     14
20        Raheem Sterling      MID      496      0        2     11
19    Oleksandr Zinchenko      DEF      522      0        0     10
21     Riccardo Calafiori      DEF      984      2        1     10
0               Ben White      DEF     1198      0        2      9
24         William Saliba      DEF     3041      2        0      6
16     Myles Lewis-Skelly      DEF     1370      1        0      3
8            Jakub Kiwior      DEF     1117      1        0      3
9                Jorginho      MID      702      0        0      2
12         Kieran Tierney      DEF      252      1        0      2
17  Nathan Butler-Oyedeji      FWD        6      0        0      1
22      Takehiro Tomiyasu      DEF        6      0        0      1
18                   Neto      GKP      180      0        0      0
2              David Raya      GKP     3420      0        0      0

In [25]:
df[
    (df["Position"] == "FWD") | 
    (df["Position"] == "MID") 
]

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
3,Declan Rice,Arsenal,England,MID,35,2833,4,7,48,18,...,21,5,1,0,0%,0,0,0,0,0.0
4,Ethan Nwaneri,Arsenal,England,MID,26,889,4,0,24,0,...,9,1,0,0,0%,0,0,0,0,0.0
5,Gabriel Jesus,Arsenal,Brazil,FWD,17,603,3,0,20,0,...,14,4,0,0,0%,0,0,0,0,0.0
7,Gabriel Martinelli,Arsenal,Brazil,MID,33,2300,8,4,55,12,...,16,1,0,0,0%,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Mateus Mané,Wolverhampton Wanderers,England,MID,1,1,0,0,0,0,...,0,0,0,0,0%,0,0,0,0,0.0
548,Matheus Cunha,Wolverhampton Wanderers,Brazil,MID,33,2600,15,6,110,4,...,42,4,0,0,0%,0,0,0,0,0.0
552,Pablo Sarabia,Wolverhampton Wanderers,Spain,MID,23,805,3,0,17,0,...,16,3,0,0,0%,0,0,0,0,0.0
555,Rodrigo Gomes,Wolverhampton Wanderers,Portugal,MID,25,797,2,0,7,0,...,4,0,0,0,0%,0,0,0,0,0.0
559,Tommy Doyle,Wolverhampton Wanderers,England,MID,24,475,0,1,9,0,...,5,1,0,0,0%,0,0,0,0,0.0

In [26]:
df["Club"].nunique()

21

In [27]:
df["Club"].unique()

<StringArray>
[                'Arsenal',             'Aston Villa',
             'Bournemouth',               'Brentford',
                'Brighton',  'Brighton & Hove Albion',
                 'Chelsea',          'Crystal Palace',
                 'Everton',                  'Fulham',
            'Ipswich Town',          'Leicester City',
               'Liverpool',         'Manchester City',
       'Manchester United',        'Newcastle United',
       'Nottingham Forest',             'Southampton',
       'Tottenham Hotspur',         'West Ham United',
 'Wolverhampton Wanderers']
Length: 21, dtype: str

In [39]:
regular_forwards = df[
    (df["Position"] == "FWD") &
    (df["Minutes"] >= 900)
]

len(regular_forwards)

36